version: '3.8'
services: 
    mongo:
        image: mongo
        restart: always
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: testing
        volumes: 
            - mongo-data:/data/db
            - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
    
    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: pass
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: testing
            ME_CONFIG_MONGODB_SERVER: mongo
volumes: 
    mongo-data:
