AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for tax-calculator

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  MONGO_DB_NAME: 
    Type: String
    Description: The name of mongo db
  MONGO_DB_CONNECTION_STR:
    Type: String
    Description: Connection string to mongo db

Resources:
  TaxCalculatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/TaxCalculator/
      Handler: TaxCalculator::TaxCalculator.Function::FunctionHandler
      Runtime: dotnetcore3.1
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          MONGO_DB_CONNECTION_STR: !Ref MONGO_DB_CONNECTION_STR
          MONGO_DB_NAME: !Ref MONGO_DB_NAME
      Events:
        TaxCalculator:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tax/{amount}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TaxCalculatorApi:
    Description: "API Gateway endpoint URL for Prod stage for Tax Calculator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tax/"
  TaxCalculatorFunction:
    Description: "Tax Calculator Lambda Function ARN"
    Value: !GetAtt TaxCalculatorFunction.Arn
  TaxCalculatorFunctionIamRole:
    Description: "Implicit IAM Role created for Tax Calculator function"
    Value: !GetAtt TaxCalculatorFunctionRole.Arn
