version: '3.8'
services: 
    mongo:
        image: mongo
        restart: always
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME 
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
            MONGO_DB_NAME: $MONGO_DB_NAME
        volumes: 
            - mongo-data:/data/db
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    
    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            #Just wants to make thing simpler to reuse the username and password, do not do that in production environment
            ME_CONFIG_BASICAUTH_USERNAME: $MONGO_INITDB_ROOT_USERNAME
            ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
            ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
            ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
            ME_CONFIG_MONGODB_SERVER: mongo
volumes: 
    mongo-data:
